docs_dir: doc/book/ru
pages:
    - index.md
    - 'Object Manager': 'object-manager.md'
    - 'Entity Manager':
      - 'Описание EntityManager': 'entity-manager.md'
      - 'Автоопределение класса сущности по его интерфейсу': 'auto-resolve-entity-class-name.md'
    - 'Определение Discriminator Maps на уровне сущностей-потомков': 'defining-discriminator-maps-at-child-level.md'
    - 'Гидраторы':
      - 'Абстрактная фабрика для создания \DoctrineModule\Stdlib\Hydrator\DoctrineObject': 'doctrine-object-hydrator.md'
    - 'Сервисы':
      - 'ObjectManagerServiceInterface': 'object-manager-service.md'
site_name: module-options
site_description: 'Набор готовых решений для работы с Doctrine2 на проектах zf2'
repo_url: 'https://github.com/nnx-framework/doctrine'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX</a>'
